name: .NET Core Desktop

on:
  push:
    branches: [ "main","ultimate_version" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Configura la versión de .NET (Asegúrate que sea la que usas en tu HP 255)
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Agregamos MSBuild que es el motor de compilación de Windows Forms
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # 1. Restaurar dependencias (esto descarga paquetes si usaste NuGet)
    - name: Restore dependencies
      run: dotnet restore

    # 2. Compilar la solución (Build)
    # Esto verifica que tu código de Ventas y Usuarios no tenga errores
    - name: Build NovaMarket
      run: dotnet build --configuration Release --no-restore

    # 3. Subir el ejecutable (.exe) como evidencia para el docente
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NovaMarket-Ejecutable
        path: |
          **/bin/Release/**
